= dnsclass:from_to
Lauri Moisio <l@arv.io>
Version 0.0.2, 2019.04.08
:ext-relative: {outfilesuffix}

== Function

dnsclass:from_to - Transform an identifying term from one type to another

== Description

[source,erlang]
----
from_to(
  Value :: atom() | 0..16#FFFF | string(),
  From :: 'value' | 'module' | 'atom' | 'masterfile_token',
  To   :: 'value' | 'module' | 'atom' | 'masterfile_token' | 'masterfile_token_generic')
    -> atom() | 0..16#FFFF | string().
----

Transform an identifying term from one type to another.

Mnemonic: `from_to(hs, atom, value)` -- "Transform hs *from_* atom *to* value".

== Arguments

Value::

Term to transform. If it is a `'masterfile_token'` string, character case does not matter. Generic form is accepted in the `'masterfile_token'` case.

From::

Transform from type

To::

Transform to type

== Return value

On success, the identifying term in type `To` is returned.

If the translation was not possible, the original `Value` is returned.

Summarizing: On success a different value is returned, on error the original value is returned.

== Examples

[source,erlang]
----
1 = dnsclass:from_to(in, atom, value),
"in" = dnsclass:from_to(in, atom, masterfile_token),
"class1" = dnsclass:from_to(in, atom, masterfile_token_generic),
dnsclass_in = dnsclass:from_to(in, atom, module),

in = dnsclass:from_to(1, value, atom),
dnsclass_in = dnsclass:from_to(1, value, module),
"in" = dnsclass:from_to(1, value, masterfile_token),
"class1" = dnsclass:from_to(1, value, masterfile_token_generic),

% An unknown value
100 = dnsclass:from_to(100, value, atom),
100 = dnsclass:from_to("class100", masterfile_token, value),
"class100" = dnsclass:from_to(100, value, masterfile_token),
"class100" = dnsclass:from_to("class100", masterfile_token, module).
----

== Changelog

* *0.0.2*
** String case is ignored when transforming from `'masterfile_token'` values
** `'masterfile_token'` values can also be in the generic format (`"CLASS1"`)
** Added `'masterfile_token_generic'` as a possible value for `To`
** Add missing documentation/spec for `'masterfile_token'` as a value of `From` and `To`
* *0.0.0* Function added

== See also

link:dnsclass{ext-relative}[dnsclass]
