= dnsfile:write_resources
Lauri Moisio <l@arv.io>
Version 0.0.2, 2019.01.29
:ext-relative: {outfilesuffix}

== Name

dnsfile:write_resources - Write resource records to a file

== Description

[source,erlang]
----
write_resources(Path :: string(), Resources :: [dnslib:resource()])
    -> write_resources(Path, Resources, []).

write_resources(Path :: string(), Resources :: [dnslib:resource()], Opts :: [write_resources_opt()])
    -> 'ok'.
----

Write resource records to a file. Inverse of link:dnsfile.consult{ext-relative}[`dnsfile:consult/1,2`].

== Types

=== write_resources_opt()

[source,erlang]
write_resources_opt() =
      'generic',
    | 'append'.

The default value for each option -- when one exists -- is given in parentheses next to the option.

`'generic'`::

link:https://tools.ietf.org/rfc/rfc3597.txt[RFC3597] specifies a generic syntax for representing unknown resource types and classes in DNS master files. Setting this option causes all resources -- known and unknown alike -- to be written in the aforementioned generic form.

`'append'`::

If option `'append'` is provided, writes take place at the end of the file. Otherwise if the file `Path` exists, it is truncated and the `Resources` will replace the current contents of the file.

== Arguments

Path::

Path of the file to which resources will be written. Created if it does not exist, overwritten if it does exist.

Resources::

Resources which are to be written to the file

Opts::

Options to alter the behavior of `write_resources`

== Return value

On success `'ok'` atom is returned.

== Notes

Although `write_resources` can store the passed resources in master file syntax, the resulting file will *not* be pretty or user-friendly.

== Examples

[source,erlang]
----
Resource = {[<<"arv">>,<<"io">>], a, in, 60, {0,0,0,0}},
ok = dnsfile:write_resources("/tmp/test.zone", [Resource]).
----

== Changelog

* *0.0.2*
** Option `'append'` added
** Option `{'generic', boolean()}` replaced with `'generic'`. *Incompatible change*
* *0.0.1* Function added

== See also

link:dnsfile.consult{ext-relative}[dnsfile:consult],
link:dnsfile.read_file{ext-relative}[dnsfile:read_file],
link:dnsfile{ext-relative}[dnsfile]
