= dnsmsg:set_response_section
Lauri Moisio <l@arv.io>
Version 0.0.1, 2019.01.18
:ext-relative: {outfilesuffix}

== Name

dnsmsg:set_response_section - Set a section of a future response to some list of resources

== Description

[source,erlang]
----
set_response_section(
  Msg :: dnsmsg:message(),
  Section :: 'answer' | 'authority' | 'additional',
  List :: [dnslib:resource()])
    -> dnsmsg:message().
----

Set a section of a future response to some list of resources.

== Arguments

Msg::

A request message. When the response to this message is created, set section will be present in it.

Section::

Section to set

List::

List of resources

== Return value

A request message containing the added resource(s) is returned.

When `dnmsg:response` is executed on the returned request message, the added resources will be present in the created response.

Trying to add questions will crash the application.

== Examples

[source,erlang]
----
Resource = dnslib:resource("arv.io", a, in, 60, {0,0,0,0}),
Req = dnsmsg:new(),
Req1 = dnsmsg:set_response_section(Req, answer, [Resource]),
#{'Answers' := [Resource]} = Res = dnsmsg:response(Req1).
----

== Changelog

* *0.0.0* Function added

== See also

link:dnsmsg.response{ext-relative}[dnsmsg:response],
link:dnsmsg{ext-relative}[dnsmsg]
