= dnslib 0.0.2 Manual
Lauri Moisio <l@arv.io>
Version 0.0.2, 2019.04.09
:ext-relative: {outfilesuffix}

== Introduction

dnslib will be a standards compliant, reliable and extensible library for working with Domain Name System (DNS) data. At the time of writing, however, it lacks the testing to verify it as any of the aforementioned.

dnslib can be included in an application when it is necessary to work with DNS master files or DNS wire format.
A variety of functionality for working with DNS messages and assorted data types is included.

The reader should note that dnslib *does not* implement any of the networking functionality of DNS. While it will get an application up to the binary representation of a DNS message, dnslib will not send that binary anywhere.

You can find the source code for link:https://github.com/lateio/dnslib[dnslib on Github].

=== Supported platforms

dnslib is developed and tested for Erlang/OTP 20 and newer, on macOS and Linux.

However, as dnslib does not rely on anything particularly exotic in Erlang, it may well work on older versions of Erlang and on other platforms. Extending support to older versions and other platforms is not out of the question, if the need arises. Given the fact that dnslib relies heavily on maps, Erlang/OTP 17 is likely the earliest version of Erlang for which the idea of compatibility should be entertained.

If and when dnslib implements punycode/internationalized domain names (IDN) functionality, the need to normalize Unicode strings may restrict supported Erlang versions to OTP 20 and newer, because OTP 20 introduced the necessary Unicode string normalization functions and re-implementing anything Unicode normalization related seems like a bad use of everyone's time. Alternatively, it is possible that dnslib carves out the IDN functionality as an exception on older OTP versions. All this remains to be determined one way or another.

=== Versioning

dnslib is a new project and limited stability should be expected for versions before 1.0.0 -- although nobody likes breaking changes and we try to avoid them. Additionally, for the foreseeable future dnslib will go the way that the requirements of the link:https://github.com/lateio/kurremkarmerruk[Kurremkarmerruk DNS server] dictate.

After 1.0.0, dnslib will adopt the standard semantic versioning.

=== Upgrading

New dnslib releases entail changes. You can find link:changelog_new{ext-relative}[new features] and link:changelog_old{ext-relative}[changes to old ones] in 0.0.2 listed link:changelog{ext-relative}[together here].

== Quick start

[source,erlang]
----
% Request
Question = dnslib:question("arv.io", a, in),
Request0 = dnsmsg:new(#{}, Question),
{ok, ReqBinLen, ReqBin} = dnswire:to_binary(Request0),
ReqBinLen = byte_size(ReqBin),
{ok, Request0, <<>>} = dnswire:from_binary(ReqBin),

% Response
Answer = dnslib:resource("arv.io IN 60 A 127.0.0.1"),
Request1 = dnsmsg:add_response_answer(Request0, Answer),
Response = dnsmsg:response(Request1),
{ok, ResBinLen, ResIolist} = dnswire:to_iolist(Response),
ResBin = iolist_to_binary(ResIolist),
ResBinLen = byte_size(ResBin),
{ok, Response, <<"Trailing">>} = dnswire:from_binary(<<ResBin/binary, "Trailing">>),

% Make sense of the response
{ok, [{Question, ok, [Answer]}]} = dnsmsg:interpret_response(Response),

% Keep the answer safe...
ok = dnsfile:write_resources("/BleepBloop/treasures", [Answer]),

% ...But but take a good look at it every now and then
{ok, [Answer]} = dnsfile:consult("/BleepBloop/treasures").
----

== Modules

* link:dnsclass{ext-relative}[dnsclass] - Behavior for class modules and related functions
* link:dnsfile{ext-relative}[dnsfile] - Handle DNS master files
* link:dnslib{ext-relative}[dnslib] - General DNS functionality
* link:dnsmsg{ext-relative}[dnsmsg] - Create and work with DNS messages
* link:dnsrr{ext-relative}[dnsrr] - Behavior for resource record modules and related functions
* link:dnswire{ext-relative}[dnswire] - Transform messages from and to binary wire format
* link:dnszone{ext-relative}[dnszone] - Functionality related to DNS zones

== Standards Compliance

=== Documents

* Original DNS spec: link:https://tools.ietf.org/html/rfc1034[RFC1034] and link:https://tools.ietf.org/html/rfc1035[RFC1035]
* Host names may begin with a digit: link:https://tools.ietf.org/html/rfc1123[RFC1123]
* Original spec clarification: link:https://tools.ietf.org/html/rfc2181[RFC2181]
* DNS Cookies: link:https://tools.ietf.org/html/rfc7873[RFC7873]
* NAPTR: link:https://tools.ietf.org/html/rfc2915[RFC2915]
* DNS SRV Records: link:https://tools.ietf.org/html/rfc2782[RFC2782]
* IPv6 (AAAA) Records: link:https://tools.ietf.org/html/rfc3596[RFC3596]
* DNS case insensitivity: link:https://tools.ietf.org/html/rfc4343[RFC4343]
* URI DNS Records: link:https://tools.ietf.org/html/rfc7553[RFC7553]
* Extension Mechanism for DNS: link:https://tools.ietf.org/rfc/rfc6891.txt[RFC6891]
* The Role of Wilcards in the DNS: link:https://tools.ietf.org/rfc/rfc4592.txt[RFC4592]
* Handling of Unknown DNS Resource Record (RR) Types: link:https://tools.ietf.org/rfc/rfc3597.txt[RFC3597]
* Binary Labels in the Domain Name System: link:https://tools.ietf.org/html/rfc2673[RFC2673]

=== Supported Extended Label Types

* Binary Labels

=== Supported resource types

* A
* AAAA
* ALL/$$*$$ (QTYPE)
* AXFR (QTYPE)
* CNAME
* HINFO
* IXFR (QTYPE)
* MAILA (QTYPE)
* MAILB (QTYPE)
* MB, MD, MF, MG, MR
* MINFO
* MX
* NAPTR
* NS
* NULL
* OPT
* PTR
* SOA
* SRV
* TXT
* URI
* WKS

dnslib can also passthrough unrecognized classes, resource types and their data, if need be.
